import type { Metadata } from "next";
import "./globals.css";

import { JetBrains_Mono } from "next/font/google";
import { Header } from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import Loader from "@/components/shared/loader";
import Script from "next/script";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["cyrillic"],
  variable: "--font-jetbrainsmono",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "НЭГ ИТ | Главная",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={jetBrainsMono.className}>
        {/* <Script
          strategy="afterInteractive"
          src="https://www.google.com/recaptcha/enterprise.js?render=6LffCI4qAAAAAP3jRcO45WNQAfiI_hznVcukDQBZ"
        /> */}
        <Loader>
          <Header />
          {children}
          {modal}
          <Footer />
        </Loader>
      </body>
    </html>
  );
}
