import type { Metadata } from "next";

import { JetBrains_Mono } from "next/font/google";
import { Header } from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import Loader from "@/components/shared/loader";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["cyrillic"],
  variable: "--font-jetbrainsmono",
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "НЭГ ИТ | Автоматизация процессов",
  description: "Generated by create next app",
};

export default function AutomationLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Loader>{children}</Loader>;
}
